#!/bin/bash

read -p "Enter a URL for the image file" URL

curl $URL > fileimage1 

aws s3 cp fileimage1 s3://ds2022-sxk2eh/

echo "https://s3.amazonaws.com/ds2022-sxk2eh/fileimage1"

aws s3 presign --expires-in 604800 s3://ds2022-sxk2eh/fileimage1


